#!/usr/bin/env python3
"""
Scrape Pitara science-for-kids articles and save in JSON format.
This script processes the URLs discovered via firecrawl map and saves articles.
"""

import json
import os
import re
from datetime import datetime

# Article URLs discovered from firecrawl map (filtered to exclude pagination and category pages)
ARTICLE_URLS = [
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-fish-survive-in-icy-waters",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/penguin-sweaters",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-artificial-intelligence",
    "https://www.pitara.com/science-for-kids/5ws-and-h/which-mammal-lays-eggs",
    "https://www.pitara.com/science-for-kids/5ws-and-h/whys-the-sun-red-during-sunrise-and-sunset",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/fish-that-live-in-the-desert",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-a-virus",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-does-a-nuclear-bomb-differ-from-a-conventional-bomb",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-makes-the-egg-shell-so-strong",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-plants-lean-toward-sunlight",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-invented-the-pen",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-did-numerals-originate",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-dont-birds-on-a-wire-get-a-shock",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-houseflies-spread-diseases",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-cloning",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-does-water-stay-cool-in-matkas",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-happens-after-an-earthquake",
    "https://www.pitara.com/science-for-kids/5ws-and-h/which-is-the-fastest-animal-on-earth",
    "https://www.pitara.com/science-for-kids/5ws-and-h/which-is-the-oldest-living-creature",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-ants-walk-in-a-line",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-water-harvesting",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-did-christianity-come-to-india",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-clocks-run-clockwise",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-cant-the-sun-melt-snow",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-we-have-wrinkly-fingers-after-swimming",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-are-human-voices-different",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/king-of-fruits-history-of-mango",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-did-the-pineapple-get-its-name",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-is-the-dead-sea-dead",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-the-mystery-of-dracula",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-the-potato-fruit-or-vegetable",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-exotic-peacock",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-importance-of-the-mangrove-forest",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-does-the-steam-engine-work",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/why-is-a-hippopotamus-called-a-river-horse",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/himalayas-have-a-deep-impact-on-the-climate-of-the-world",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-doesnt-our-stomach-get-digested",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-does-the-sun-follow-you",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-did-jazz-originate",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-is-it-harder-to-walk-uphill",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-pluto-a-star-or-a-comet",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/global-warming-melting-kingdom-of-the-polar-bear",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-far-away-are-the-stars",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-is-the-bridge-of-sighs-so-called",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-we-get-tired",
    "https://www.pitara.com/science-for-kids/living-world-for-kids/is-tomato-a-vegetable-or-a-fruit",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/how-does-the-lotus-flower-clean-itself",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-nails-grow",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-kind-of-horses-did-knights-ride",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-does-dew-form",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-plants-bear-fruit",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-ducks-stay-in-water-and-not-get-wet",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-fish-which-changes-from-female-to-male",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-invented-the-photocopying-machine",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-stars-twinkle",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-wonderful-world-of-insects",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-does-milk-spill-over-when-it-boils",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-did-shoes-come-from",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/a-fish-with-three-hearts-cuttlefish",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-flies-have-compound-eyes",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-does-a-submarine-work",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-or-what-is-a-gladiator",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-does-ice-float",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-is-the-mediterranean-sea-blue",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/do-bananas-grow-on-trees",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-the-origin-of-silk-fabric",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-bad-is-the-sting-of-a-scorpion",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-a-volcano",
    "https://www.pitara.com/science-for-kids/living-world-for-kids/can-plants-be-parasites",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-humans-sweat",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-does-satellite-tv-work",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-the-weight-of-air",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-wool-came-into-existence",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-doctors-examine-the-pulse",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-a-tornado",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-are-earthquakes-recorded",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-invented-hello",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/an-organism-that-is-visible-from-space",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-was-the-berlin-wall-built",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-satellites-stay-up",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-does-cutting-onions-make-us-cry",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-does-time-start-in-greenwich",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-mysterious-case-of-the-neem-tree",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-magical-rainforest",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-daylight-saving-time",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-cats-always-land-on-their-feet",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-earthquakes-happen",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-does-the-pigeon-post-operate",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-cloud-seeding",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-end-of-living-the-beginning-of-survival",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-the-ozone-hole",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/dolphin-in-the-mirror",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-discovered-vaccination",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-secrets-of-the-ocean-floor",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-we-cup-our-hands-when-we-shout",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/can-a-fish-be-an-amphibian",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-is-paper-perfumed",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/my-life-the-tale-of-a-butterfly",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-cotton-candy",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-meteorites-strike-the-earth",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-deadly-king-cobra",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-animals-camouflage",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/treaty-on-global-warming",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-truth-about-zoos",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-is-jelly-formed",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/how-lizards-defy-gravity",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-are-zebras-striped",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-horses-need-shoes",
    "https://www.pitara.com/science-for-kids/5ws-and-h/elevator-physics",
    "https://www.pitara.com/science-for-kids/5ws-and-h/which-insects-live-the-longest",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-people-kiss-under-the-mistletoe",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/tale-of-the-woolly-mammoth",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-did-the-yo-yo-originate",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/tree-rings-tell-many-tales",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-are-canal-locks",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-did-sign-language-originate",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-the-trail-behind-a-jet",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-airplanes-have-wings",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-did-pencils-originate",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-do-penguins-live",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-humans-balance-on-two-legs",
    "https://www.pitara.com/science-for-kids/living-world-for-kids/does-the-black-widow-spider-kill-her-mate",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-beavers-build-dams",
    "https://www.pitara.com/science-for-kids/5ws-and-h/can-two-people-have-identical-fingerprints",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-many-kinds-of-rhinos-are-there",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/venice-is-sinking",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-onions-make-us-cry",
    "https://www.pitara.com/science-for-kids/5ws-and-h/the-hows-and-whys-of-bubble-gum",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/jupiters-new-moon",
    "https://www.pitara.com/science-for-kids/5ws-and-h/when-will-the-oceans-of-the-earth-overflow",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-earthquakes-occur",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-the-secret-of-the-windmill",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-are-komodo-dragons",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-ham-radio",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-does-a-helicopter-hover",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/the-hottest-way-to-catch-crooks",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-an-earthquake",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-they-make-an-igloo",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-does-cola-fizz",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/different-colours-of-honey",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-we-blink",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-to-do-during-an-earthquake",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-turtles-and-tortoises-live-so-long",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-animals-communicate",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/planets-planets-and-more-planets",
    "https://www.pitara.com/science-for-kids/5ws-and-h/is-bamboo-a-grass",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-plastic-menace",
    "https://www.pitara.com/science-for-kids/5ws-and-h/do-whales-and-dolphins-see-blue",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-invented-band-aid",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/roach-sense",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-did-the-safety-match-originate",
    "https://www.pitara.com/science-for-kids/5ws-and-h/which-is-the-worlds-oldest-working-locomotive",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-flush-toilets-work",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-we-see-a-face-on-the-moon",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-a-tsunami",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-toothpaste-did-the-ancients-use",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/what-is-vetiver-grass",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/can-fish-lay-eggs-in-the-mouth",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-invented-traffic-lights",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-locusts-swarm",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-mad-cow-disease",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-are-some-reptiles-brightly-coloured",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/mosquito-menace",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-did-santa-claus-originate",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/dinosaur-eggs-found-in-patagonia",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/robot-that-changes-form",
    "https://www.pitara.com/science-for-kids/5ws-and-h/underground-rivers",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-is-the-ball-point-pen-called-so",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-are-some-plants-non-vegetarian",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-blood-pressure",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-human-cannonballs-fly",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/everything-is-made-of-something",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-aircrafts-have-a-black-box",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-were-the-voyager-missions",
    "https://www.pitara.com/science-for-kids/living-world-for-kids/can-frog-fly",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-chameleons-latch-on-to-prey-using-just-their-tongue",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-will-our-sun-die",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-is-snow-white",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-are-the-various-jazz-styles",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/all-human-history-is-just-10-seconds-old",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-does-a-cricket-ball-swing",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/deception-and-mimicry-among-animals-to-fool-enemies",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-are-eggs-oval",
    "https://www.pitara.com/science-for-kids/5ws-and-h/whys-it-hard-for-ketchup-to-flow",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-are-the-shaking-minarets",
    "https://www.pitara.com/science-for-kids/5ws-and-h/which-is-the-most-abundant-fruit-in-india",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/birds-which-eat-their-feathers",
    "https://www.pitara.com/science-for-kids/5ws-and-h/the-colours-of-light",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-invented-the-frisbee",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/a-new-camel-specie-discovered",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/the-scent-of-an-enemy",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/great-white-sharks-heading-for-extinction",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-a-kangaroo-rat",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-are-stars-named",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-are-frogs-different-from-toads",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/scientists-find-more-on-the-eureka-man",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-is-the-twins-day-festival-held",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/antlers-a-deer-story",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/save-rivers-lakes-from-worshippers",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-whale-hunt-is-on",
    "https://www.pitara.com/science-for-kids/5ws-and-h/do-centipedes-really-have-100-feet",
    "https://www.pitara.com/science-for-kids/5ws-and-h/whos-the-brainiest-animal-of-them-all",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/the-smart-polluters",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-dont-spiders-get-caught-in-their-webs",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-rabbits-have-buck-teeth",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-memory",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-earthworms-good-turn",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-does-sos-mean",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-can-we-correct-crooked-teeth",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-geothermal-energy",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-can-we-use-water-to-run-cars",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/excerpts-from-the-world-of-trees",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-woollens-get-holes",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-are-volcanic-tubeworms",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-stole-the-candle-wax",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-are-dry-clouds",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-an-orca-whale",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-are-truffles",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-is-the-real-mccoy",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/jellyfish-fragile-creature-of-the-sea",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-does-a-juggler-juggle",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-did-piggy-banks-come-from",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/storm-petrel-a-bird-that-walks-on-water",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/dropping-trees-from-the-sky-hydroseeding",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-are-moths-attracted-to-light",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-is-the-rare-blind-dolphin-found",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/insect-which-swims-on-its-back",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-cool-firefly",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/killing-a-tree-softly",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-the-software-for-life",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/evergreen-clothes",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/some-animal-fathers-are-great-dads-too",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/stinking-plants",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-did-the-modern-horse-originate",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-the-rubiks-cube",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-were-the-1904-olympics-such-a-disaster",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/mother-and-child-in-the-animal-kingdom",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-did-the-teddy-bear-get-its-name",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-esperanto",
    "https://www.pitara.com/science-for-kids/5ws-and-h/do-aphasics-make-great-lie-detectors",
    "https://www.pitara.com/science-for-kids/5ws-and-h/is-the-red-colobus-monkey-extinct",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-are-go-go-boots",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/long-memory-of-female-elephants-is-responsible-for-the-well-being-of-their-families",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-straightened-leaning-tower-of-pisa",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/anacondas",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/music-loving-plants-and-music-giving-plants",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-ears-pop",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-an-isbn-number",
    "https://www.pitara.com/science-for-kids/5ws-and-h/where-did-coffee-originate",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/and-now-schoolbags-online",
    "https://www.pitara.com/science-for-kids/5ws-and-h/do-raccoons-wash-their-hands-before-they-eat",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-bespectacled-bear",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-some-people-snore-more-than-others",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/shirt-that-is-a-mobile-phone",
    "https://www.pitara.com/science-for-kids/5ws-and-h/whats-biting-the-flea",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-physiotherapy",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-we-get-hiccups",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/does-a-sloth-live-its-entire-life-upside-down",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/what-is-ribotyping",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-we-yawn",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/a-lizard-that-squirts-blood-from-its-eyes",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/spiders-and-their-magical-web",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-do-spiderwebs-help-skydivers",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-truth-about-bats",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/dealing-with-the-potential-danger-of-a-meteor-hitting-earth",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/a-beautiful-ship-in-the-sky",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/its-a-zoo-out-there",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-deadliest-animal-in-the-world",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/mans-best-friend",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/marine-militants-bioinvasion-propagated-through-cargo-ships",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/logging-on-to-aliens",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/ginger-the-new-wonder-medicine",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/sea-turtles",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/space-tourism-ready-for-a-skyrocketing-holiday",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-the-origin-of-ok",
    "https://www.pitara.com/science-for-kids/5ws-and-h/which-film-stars-were-inventors-too",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/your-mobile-phone-has-a-bug",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-kind-of-creatures-are-sharks",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-tiny-world-of-ants",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/chimp-traits",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-or-where-is-the-tower-of-babel",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/looking-at-the-world-upside-down",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-does-a-train-whistle-tell-us-about-the-universe",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-kind-of-family-life-did-the-dinosaurs-have",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/amazing-facts-about-water",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-hot-and-sizzling-volcano",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/peppermint-to-chase-mosquitoes-away",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-vultures-are-dying",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/why-do-dogs-and-cats-eat-grass",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/scales-for-safety",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/whose-river",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/tail-language",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/smelling-food-with-the-tongue",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-dark-kingdom-of-uranus",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/the-cool-and-cunning-lark",
    "https://www.pitara.com/science-for-kids/5ws-and-h/which-galaxy-is-visible-to-the-eye",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/road-of-jute",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/its-a-beetles-world",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/pollution-an-old-ancestral-legacy",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-is-hair-today-gone-tomorrow",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/when-a-cat-preys-for-lunch",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/high-tech-turtle",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/footprints-on-earth",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/can-you-speak-dolphin-language",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-sold-the-eiffel-tower-twice",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/an-earth-day-fable",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-some-people-stutter",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/an-octopus-as-jar-opener",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/rhinoceros-on-the-comeback-trail",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-earth-takes-a-battering",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/excerpts-from-everything-has-a-history",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/watery-facts",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/a-smelly-new-world-on-the-web",
    "https://www.pitara.com/science-for-kids/5ws-and-h/are-fish-dumb",
    "https://www.pitara.com/science-for-kids/5ws-and-h/who-was-the-us-president-for-a-day",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-leukaemia",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-do-knuckles-pop",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/whos-who-at-the-zoo",
    "https://www.pitara.com/science-for-kids/5ws-and-h/do-some-animals-farm",
    "https://www.pitara.com/science-for-kids/5ws-and-h/when-was-the-first-circumnavigation-by-air",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/birds-sing-in-their-sleep",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/distress-signals-the-leafy-way",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-earth-is-getting-dimmer",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/this-one-is-for-your-eyes-only",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-are-q-tips",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-gardener-bird",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/so-many-monkeys",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/how-green-is-your-school",
    "https://www.pitara.com/science-for-kids/5ws-and-h/what-is-asthma",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/is-new-york-burning",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/dangerous-red-tide-in-hongkong",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/pelican-trouble",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/seasons-in-a-trees-rooted-life",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-tree-is-an-invisible-heater",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/paris-is-bugged",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/mr-fly-rubs-his-hands-with-glee",
    "https://www.pitara.com/science-for-kids/5ws-and-h/cigarette-packs-that-talk",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/rocky-planet-of-fire-and-ice",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/high-tech-crane-migration",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/in-a-minute",
    "https://www.pitara.com/science-for-kids/5ws-and-h/why-does-a-kentish-plover-parent-desert-its-family",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/squirrelling-it-away",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/excerpts-from-the-wonderful-world-of-insects",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-song-of-the-bird",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/fox",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/mutual-aid-societies",
    "https://www.pitara.com/science-for-kids/planet-earth-for-kids/the-baby-current-which-destroys",
    "https://www.pitara.com/science-for-kids/science-news-for-kids/a-train-of-villages-on-the-net",
    "https://www.pitara.com/science-for-kids/5ws-and-h/whick-book-carries-its-own-light",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-did-the-indian-postal-service-start",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-does-the-army-post-office-system-work",
    "https://www.pitara.com/science-for-kids/5ws-and-h/how-did-advertising-start-in-india",
    "https://www.pitara.com/science-for-kids/5ws-and-h/which-is-the-oldest-church-in-india",
]

def extract_category(url):
    """Extract category from URL."""
    # URL format: https://www.pitara.com/science-for-kids/{category}/{article-slug}
    parts = url.replace("https://www.pitara.com/science-for-kids/", "").split("/")
    if len(parts) >= 1:
        return parts[0]
    return "science-for-kids"

def extract_title_from_slug(url):
    """Extract title from URL slug as fallback."""
    slug = url.rstrip("/").split("/")[-1]
    # Convert slug to title
    title = slug.replace("-", " ").title()
    return title

def main():
    print(f"Total articles to process: {len(ARTICLE_URLS)}")
    print("Note: This script prepares the URL list. Use firecrawl to scrape each article.")
    
    # Save URLs to a file for reference
    output_dir = "/home/zym/Auto-Popsci/datasets/our_dataset/pitara"
    urls_file = os.path.join(output_dir, "article_urls.json")
    
    with open(urls_file, "w", encoding="utf-8") as f:
        json.dump(ARTICLE_URLS, f, indent=2, ensure_ascii=False)
    
    print(f"Saved {len(ARTICLE_URLS)} URLs to {urls_file}")
    print("\nTo scrape articles, the firecrawl MCP tool will be used.")
    
if __name__ == "__main__":
    main()

